[package]
name = "ass-easy-loop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ass-easy-loop"
path = "src/main.rs"

[lib]
name = "ass_easy_loop"
path = "src/lib.rs"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
fugit = "0.3.7"
nb = "1.1.0"
panic-halt = "1.0.0"
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.11.0", features = ["rt", "rtic-monotonic"] }
rp2040-pac = "0.6.0"
rtic = { version = "2.2.0", features = ["thumbv6-backend"] }
rtic-monotonics = { version = "2.1.0", features = ["rp2040"] }
rtic-time = "2.0.0"

# USB HID logging dependencies
usbd-hid = "0.8.2"
usb-device = "0.3.2"
heapless = "0.8.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }

# Command processing dependencies
# bitvec = "1.0.1"  // Removed due to std dependency issues on embedded targets

# Conditional dependencies for different targets
[target.'cfg(not(target_arch = "arm"))'.dependencies]
portable-atomic = "1.11"

[target.'cfg(target_arch = "arm")'.dependencies]
portable-atomic = { version = "1.11", features = ["unsafe-assume-single-core"] }

[features]
default = ["battery-logs", "pemf-logs", "system-logs", "usb-logs", "test-commands"]
std = []

# Build configuration feature flags
production = ["battery-logs", "system-logs", "performance-optimized"]
development = ["battery-logs", "pemf-logs", "system-logs", "usb-logs", "test-commands", "debug-features"]
testing = ["battery-logs", "pemf-logs", "system-logs", "usb-logs", "test-commands", "debug-features", "test-validation"]

# Command processing feature flags
command-processor = []
test-commands = []
system-state-queries = []

# Performance and optimization flags
performance-optimized = []
debug-features = []
test-validation = []

# Logging category feature flags for conditional compilation
battery-logs = []
pemf-logs = []
system-logs = []
usb-logs = []

# Convenience feature combinations
debug-logging = ["battery-logs", "pemf-logs", "system-logs", "usb-logs"]
minimal-logging = []

[dev-dependencies]
defmt = "0.3.8"
defmt-rtt = "0.4.1"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }

# Test configuration to avoid panic handler conflicts
[[test]]
name = "logging_tests"
path = "tests/logging_tests.rs"

[[test]]
name = "hardware_validation_tests"
path = "tests/hardware_validation_tests.rs"

[[test]]
name = "pemf_timing_validation_test"
path = "tests/pemf_timing_validation_test.rs"

[[test]]
name = "battery_adc_integration_test"
path = "tests/battery_adc_integration_test.rs"

[[test]]
name = "core_functionality_unit_tests"
path = "tests/core_functionality_unit_tests.rs"