[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]

# Only set embedded target for the binary, not for tests
# Tests should run on host with std support

[env]
DEFMT_LOG = "debug"
